"""Tests for echochamber.ui.controller, written from the step-5 API contract.

Written from the *spec*, not the implementation.  Nothing here needs a
microphone: every controller is driven through the ``source_factory_builder``
seam with a :class:`FileSource` replaying a WAV generated by :mod:`wave` into
``tmp_path``, and device enumeration runs against ``tests.fake_sounddevice``.
That is the whole point of those two seams -- the deployment target (Windows
ARM64) and any CI box have neither this developer's microphone nor his device
table, and a test that needs either is a test that quietly stops running.

Determinism strategy, borrowed from ``test_pipeline.py``:

* ``sample_rate=1000`` so ``1 ms == 1 frame`` and every window/hop arithmetic
  assertion reads directly off the arguments;
* ``DropPolicy.BLOCK`` plus a ring far larger than the file, so the chunk count
  is exactly ``n_windows(n, W, H)`` and nothing can be dropped or overrun;
* every wait is event-driven with a multi-second bound;
* every controller is stopped in fixture teardown, so no audio thread can
  outlive its test.

The two Qt-specific rules the contract cares about are asserted directly:
:class:`LatestChunkSink` is not a ``QObject`` (it runs on the consumer thread),
and ``stats_updated`` only ever fires on the GUI thread.
"""

from __future__ import annotations

import dataclasses
import os

# Must precede any PySide6 import: the suite has to run on a headless box.
os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

import threading
import time
import wave
from typing import Any, Callable, Iterator

import numpy as np
import pytest
from PySide6.QtCore import QObject

from echochamber.audio.devices import DeviceInfo
from echochamber.audio.pipeline import AudioPipeline
from echochamber.audio.sources.file_source import FileSource
from echochamber.audio.types import AudioChunk, DropPolicy, StreamStats
from echochamber.config import AudioConfig
from echochamber.ui.controller import (
    CaptureController,
    CaptureState,
    LatestChunkSink,
    UiStats,
)
from echochamber.ui.meters import PeakHold
from tests.fake_sounddevice import HOSTAPIS, MME, WASAPI, WDMKS, FakeSounddevice


# Generous: every wait below is event-driven, so these only bound failures.
TIMEOUT = 20.0
TIMEOUT_MS = 20_000

# How long to allow for something to *not* happen (proving absence).
QUIET_S = 0.3


# --------------------------------------------------------------------------
# helpers
# --------------------------------------------------------------------------

def ramp_int16(n: int) -> np.ndarray:
    """A distinct, strictly increasing int16 ramp -- off-by-ones are visible."""
    step = max(1, 60_000 // max(n, 1))
    idx = np.arange(n, dtype=np.int64)
    return ((idx * step) % 60_000 - 30_000).astype(np.int64)


def write_wav(path: Any, data: np.ndarray, sample_rate: int) -> Any:
    """Write a 16-bit PCM WAV; ``data`` is ``(n,)`` mono."""
    arr = np.asarray(data)
    if arr.ndim == 1:
        arr = arr.reshape(-1, 1)
    with wave.open(str(path), "wb") as w:
        w.setnchannels(arr.shape[1])
        w.setsampwidth(2)
        w.setframerate(sample_rate)
        w.writeframes(arr.astype("<i2").tobytes())
    return path


def n_windows(n_frames: int, w: int, h: int) -> int:
    """How many *full* windows fit in ``n_frames``; partial tails are dropped."""
    if n_frames < w:
        return 0
    return (n_frames - w) // h + 1


def make_config(
    window_ms: int = 100,
    hop_ms: int = 50,
    sample_rate: int = 1000,
    ring_seconds: float = 10.0,
    drop_policy: DropPolicy = DropPolicy.BLOCK,
) -> AudioConfig:
    """A config where 1 ms == 1 frame, so the geometry reads off the arguments."""
    return AudioConfig(
        sample_rate=sample_rate,
        window_ms=window_ms,
        hop_ms=hop_ms,
        ring_seconds=ring_seconds,
        drop_policy=drop_policy,
    )


def file_builder(
    path: Any,
    blocksize: int = 64,
    realtime: bool = False,
    loop: bool = False,
) -> Callable[..., Any]:
    """A ``source_factory_builder`` yielding a FileSource factory.

    The controller may call the builder with whatever it likes (the contract
    types it ``Callable[..., SourceFactory]``), so this swallows everything and
    returns the factory the pipeline expects: ``(on_audio, stats) -> source``.
    """
    def _builder(*args: Any, **kwargs: Any) -> Callable[..., FileSource]:
        def _factory(
            on_audio: Callable[[np.ndarray], None], stats: StreamStats
        ) -> FileSource:
            return FileSource(
                path,
                on_audio,
                blocksize=blocksize,
                realtime=realtime,
                loop=loop,
                stats=stats,
            )
        return _factory

    return _builder


def wait_until(pred: Callable[[], bool], timeout: float = TIMEOUT) -> bool:
    """Poll ``pred`` until it is true or ``timeout`` elapses (no event loop)."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if pred():
            return True
        time.sleep(0.005)
    return pred()


def chunk(seq: int, n: int = 100, value: float = 0.5) -> AudioChunk:
    """A plain AudioChunk for driving LatestChunkSink directly."""
    samples = np.full(n, value, dtype=np.float32)
    samples[0] = -1.0
    samples[-1] = 1.0
    return AudioChunk(
        samples=samples, start_frame=seq * n, seq=seq, sample_rate=1000
    )


def audio_threads() -> list[str]:
    """Names of pipeline threads currently alive."""
    interesting = {"file-source", "chunk-consumer"}
    return [
        t.name
        for t in threading.enumerate()
        if t.name in interesting or t.name.startswith("chunker")
    ]


# Device tables for the selection-policy tests.  The shipped fake already
# reports a WASAPI default, which is exactly the case that would let a naive
# "just use PortAudio's default" implementation pass, so these tables move the
# default onto MME (as it is on the real dev machine).
NO_WASAPI_DEVICES: list[dict[str, Any]] = [
    {"name": "Microsoft Sound Mapper - Input", "hostapi": MME,
     "max_input_channels": 2, "max_output_channels": 0,
     "default_samplerate": 44100.0},
    {"name": "Speakers (Realtek)", "hostapi": MME,
     "max_input_channels": 0, "max_output_channels": 2,
     "default_samplerate": 44100.0},
    {"name": "Stereo Mix (Realtek)", "hostapi": WDMKS,
     "max_input_channels": 2, "max_output_channels": 0,
     "default_samplerate": 48000.0},
]


# --------------------------------------------------------------------------
# fixtures
# --------------------------------------------------------------------------

@pytest.fixture
def make_controller(qapp: Any) -> Iterator[Callable[..., CaptureController]]:
    """Factory registering every controller for guaranteed teardown.

    Teardown stops each controller, so a wedged replay, chunker or consumer
    thread cannot outlive the test that created it.
    """
    created: list[CaptureController] = []

    def _make(
        config: AudioConfig | None = None,
        builder: Callable[..., Any] | None = None,
        sd_module: Any | None = None,
    ) -> CaptureController:
        controller = CaptureController(
            config=config,
            source_factory_builder=builder,
            sd_module=FakeSounddevice() if sd_module is None else sd_module,
        )
        created.append(controller)
        return controller

    yield _make

    for controller in created:
        try:
            controller.stop()
        except Exception:  # pragma: no cover - teardown must not mask failures
            pass


@pytest.fixture
def replay(
    tmp_path: Any, make_controller: Callable[..., CaptureController]
) -> Callable[..., Any]:
    """Build a controller wired to a finite, as-fast-as-possible WAV replay."""
    def _replay(
        window_ms: int = 100,
        hop_ms: int = 50,
        n_frames: int = 1000,
        blocksize: int = 64,
        realtime: bool = False,
        loop: bool = False,
        ring_seconds: float = 10.0,
        drop_policy: DropPolicy = DropPolicy.BLOCK,
        sd_module: Any | None = None,
    ) -> tuple[CaptureController, AudioConfig, int]:
        cfg = make_config(
            window_ms=window_ms,
            hop_ms=hop_ms,
            ring_seconds=ring_seconds,
            drop_policy=drop_policy,
        )
        path = write_wav(
            tmp_path / f"replay_{window_ms}_{hop_ms}_{n_frames}.wav",
            ramp_int16(n_frames),
            cfg.sample_rate,
        )
        controller = make_controller(
            config=cfg,
            builder=file_builder(
                path, blocksize=blocksize, realtime=realtime, loop=loop
            ),
            sd_module=sd_module,
        )
        controller.refresh_devices()
        return controller, cfg, n_frames

    return _replay


# ==========================================================================
# PeakHold -- pure logic, no Qt, no clock
# ==========================================================================

def test_peak_hold_starts_at_zero() -> None:
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    assert hold.value == pytest.approx(0.0)


def test_a_higher_level_is_taken_immediately() -> None:
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)

    assert hold.update(0.5, 0.0) == pytest.approx(0.5)
    assert hold.value == pytest.approx(0.5)
    assert hold.update(0.8, 0.1) == pytest.approx(0.8), (
        "a level above the current value must take it immediately -- the whole "
        "point of a peak meter"
    )
    assert hold.value == pytest.approx(0.8)


def test_update_returns_the_same_value_the_property_reports() -> None:
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    for i, level in enumerate([0.2, 0.9, 0.1, 0.4]):
        returned = hold.update(level, i * 0.05)
        assert returned == pytest.approx(hold.value), (
            "update() must return the value it just computed"
        )


def test_the_value_is_held_flat_for_hold_s() -> None:
    """StreamStats.peak_level is last-block-only; the hold is what makes it readable."""
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    hold.update(0.8, 0.0)

    now = 0.0
    while now < 0.95:
        now += 0.05
        value = hold.update(0.0, now)
        assert value == pytest.approx(0.8, abs=1e-6), (
            f"at t={now:.2f}s (hold_s=1.0) the value must still be the held "
            f"peak 0.8, got {value}"
        )


def test_a_new_peak_restarts_the_hold_window() -> None:
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    hold.update(0.4, 0.0)
    hold.update(0.9, 0.6)          # new peak at 0.6 -> hold now runs to 1.6

    assert hold.update(0.0, 1.5) == pytest.approx(0.9, abs=1e-6), (
        "the hold window must restart when a new peak is taken, otherwise a "
        "loud passage decays from when the meter first moved"
    )


def test_the_value_decays_at_roughly_decay_db_per_s_after_the_hold() -> None:
    """20 dB/s means a factor of 10 every second, once the hold has expired."""
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    hold.update(1.0, 0.0)

    now = 0.0
    while now < 1.5 - 1e-9:
        now = round(now + 0.05, 6)
        hold.update(0.0, now)
    half = hold.value
    assert 0.24 < half < 0.40, (
        f"0.5 s past a 1.0 s hold at 20 dB/s is -10 dB (~0.316), got {half}"
    )

    while now < 2.0 - 1e-9:
        now = round(now + 0.05, 6)
        hold.update(0.0, now)
    full = hold.value
    assert 0.06 < full < 0.15, (
        f"1.0 s past the hold at 20 dB/s is -20 dB (~0.100), got {full}"
    )
    assert full < half, "the decay must be monotonic while the input stays low"


def test_a_gentler_decay_rate_decays_more_slowly() -> None:
    fast = PeakHold(hold_s=0.5, decay_db_per_s=40.0)
    slow = PeakHold(hold_s=0.5, decay_db_per_s=10.0)
    for h in (fast, slow):
        h.update(1.0, 0.0)

    now = 0.0
    while now < 1.5 - 1e-9:
        now = round(now + 0.05, 6)
        fast.update(0.0, now)
        slow.update(0.0, now)

    assert fast.value < slow.value, (
        f"decay_db_per_s must actually govern the rate: 40 dB/s gave "
        f"{fast.value}, 10 dB/s gave {slow.value}"
    )


def test_the_value_never_goes_negative() -> None:
    hold = PeakHold(hold_s=0.1, decay_db_per_s=60.0)
    hold.update(1.0, 0.0)

    now = 0.0
    for _ in range(200):
        now = round(now + 0.5, 6)
        value = hold.update(0.0, now)
        assert value >= 0.0, f"a decaying peak must never go below 0.0, got {value}"
    assert hold.value < 1e-3, "after 100 s at 60 dB/s the meter must be at rest"


def test_a_negative_level_does_not_drive_the_value_negative() -> None:
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    assert hold.update(-0.5, 0.0) >= 0.0
    assert hold.value >= 0.0


def test_reset_clears_the_held_value() -> None:
    hold = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    hold.update(0.9, 0.0)
    assert hold.value == pytest.approx(0.9)

    hold.reset()
    assert hold.value == pytest.approx(0.0), "reset() must clear the held peak"

    assert hold.update(0.3, 100.0) == pytest.approx(0.3), (
        "after reset() the next level is taken immediately, whatever the clock"
    )


def test_peak_hold_never_reads_the_clock() -> None:
    """Identical `now` sequences must give identical values, however long the
    wall clock says the test took.  Reading time.monotonic() internally would
    make the meter untestable and its behaviour scheduler-dependent."""
    a = PeakHold(hold_s=1.0, decay_db_per_s=20.0)
    b = PeakHold(hold_s=1.0, decay_db_per_s=20.0)

    schedule = [(1.0, 0.0), (0.0, 0.5), (0.0, 1.4), (0.0, 2.2), (0.7, 2.3)]
    for level, now in schedule:
        a.update(level, now)
        time.sleep(0.02)           # real time passes only for `a`
        b.update(level, now)

    assert a.value == pytest.approx(b.value, rel=1e-9, abs=1e-12), (
        f"PeakHold must depend only on the supplied `now`: {a.value} != {b.value}"
    )


# ==========================================================================
# LatestChunkSink -- runs on the consumer thread, so it must not touch Qt
# ==========================================================================

def test_latest_chunk_sink_is_not_a_qobject() -> None:
    """The sink runs on the consumer thread; a QObject there is the bug the
    whole polling design exists to prevent."""
    assert not issubclass(LatestChunkSink, QObject), (
        "LatestChunkSink must not be a QObject: it is called from the audio "
        "consumer thread, which may never touch Qt"
    )
    sink = LatestChunkSink()
    assert not isinstance(sink, QObject)
    assert not hasattr(sink, "emit"), "a recording sink emits nothing"


def test_latest_chunk_sink_records_the_newest_seq() -> None:
    sink = LatestChunkSink(preview_points=64)
    for k in range(5):
        sink.on_chunk(chunk(k))

    seq, preview = sink.snapshot()
    assert seq == 4, f"snapshot() must report the newest chunk's seq, got {seq}"
    assert isinstance(preview, np.ndarray)
    assert preview.size > 0
    sink.close()


def test_latest_chunk_sink_snapshot_before_any_chunk_is_safe() -> None:
    sink = LatestChunkSink(preview_points=32)
    seq, preview = sink.snapshot()

    assert isinstance(seq, int)
    assert seq < 0, (
        f"with no chunk yet there is no sequence number to report; expected a "
        f"negative sentinel, got {seq}"
    )
    assert isinstance(preview, np.ndarray)
    sink.close()


def test_latest_chunk_sink_snapshot_returns_a_copy() -> None:
    """Mutating the returned preview must not corrupt what the GUI reads next."""
    sink = LatestChunkSink(preview_points=64)
    sink.on_chunk(chunk(0))

    _, first = sink.snapshot()
    before = first.copy()
    first += 42.0

    _, second = sink.snapshot()
    assert np.array_equal(second, before), (
        "snapshot() must return a copy; the caller scribbled on it and the "
        "next snapshot changed"
    )
    sink.close()


def test_latest_chunk_sink_does_not_alias_the_chunk_samples() -> None:
    sink = LatestChunkSink(preview_points=1024)
    c = chunk(0, n=256)
    sink.on_chunk(c)
    original = c.samples.copy()

    _, preview = sink.snapshot()
    preview[:] = 0.0

    assert np.array_equal(c.samples, original), (
        "the preview must not be a view into the chunk the pipeline still owns"
    )
    sink.close()


@pytest.mark.parametrize("preview_points", [8, 64, 512])
@pytest.mark.parametrize("n_samples", [16, 3000, 48_000])
def test_preview_is_decimated_to_at_most_preview_points(
    preview_points: int, n_samples: int
) -> None:
    """A 3 s window at 16 kHz is 48000 samples; the GUI cannot draw them all."""
    sink = LatestChunkSink(preview_points=preview_points)
    sink.on_chunk(chunk(0, n=n_samples))

    _, preview = sink.snapshot()
    assert preview.ndim == 1
    assert 0 < preview.size <= preview_points, (
        f"a {n_samples}-sample chunk must be decimated to at most "
        f"{preview_points} points, got {preview.size}"
    )
    sink.close()


def test_latest_chunk_sink_close_is_safe_and_idempotent() -> None:
    sink = LatestChunkSink()
    sink.on_chunk(chunk(0))
    sink.close()
    sink.close()


# ==========================================================================
# UiStats
# ==========================================================================

def full_stats(**overrides: Any) -> UiStats:
    """Construct a UiStats with every contract field populated."""
    fields: dict[str, Any] = {
        "state": CaptureState.RUNNING,
        "frames_captured": 16_000,
        "chunks_emitted": 14,
        "chunks_dropped": 2,
        "overruns": 1,
        "xruns": 3,
        "peak_level": 0.7,
        "rms_level": 0.2,
        "display_peak": 0.8,
        "elapsed_s": 1.25,
        "latency_ms": 22.0,
    }
    fields.update(overrides)
    return UiStats(**fields)


def test_ui_stats_carries_every_contract_field() -> None:
    names = {f.name for f in dataclasses.fields(UiStats)}
    required = {
        "state",
        "frames_captured",
        "chunks_emitted",
        "chunks_dropped",
        "overruns",
        "xruns",
        "peak_level",
        "rms_level",
        "display_peak",
        "elapsed_s",
        "latency_ms",
        "message",
    }
    missing = required - names
    assert not missing, f"UiStats is missing contract fields: {sorted(missing)}"


def test_ui_stats_message_defaults_to_empty() -> None:
    assert full_stats().message == ""


def test_ui_stats_is_frozen() -> None:
    """The snapshot crosses into the widgets; nothing may edit it in place."""
    stats = full_stats()
    with pytest.raises((dataclasses.FrozenInstanceError, AttributeError)):
        stats.frames_captured = 99  # type: ignore[misc]
    assert stats.frames_captured == 16_000


# ==========================================================================
# refresh_devices() and the WASAPI-preferring default
# ==========================================================================

def test_refresh_devices_populates_devices_and_emits(
    make_controller: Callable[..., CaptureController]
) -> None:
    sd = FakeSounddevice()
    controller = make_controller(sd_module=sd)
    seen: list[Any] = []
    controller.devices_changed.connect(seen.append)

    devices = controller.refresh_devices()

    assert devices, "the fake device table has input devices"
    assert all(isinstance(d, DeviceInfo) for d in devices)
    assert list(controller.devices) == list(devices), (
        "refresh_devices() must store what it returns"
    )
    assert "Speakers (Realtek)" not in [d.name for d in devices], (
        "output-only devices must not reach the picker"
    )
    assert len(seen) == 1, f"devices_changed must fire exactly once, got {len(seen)}"
    assert list(seen[0]) == list(devices)


def test_default_selection_prefers_wasapi_over_the_reported_default(
    make_controller: Callable[..., CaptureController]
) -> None:
    """Measured on real hardware the system default is MME: ~30 ms latency, and
    it bypasses the auto-convert path the WASAPI source exists to exercise."""
    sd = FakeSounddevice(default_input=0)      # index 0 is the MME mapper
    controller = make_controller(sd_module=sd)

    controller.refresh_devices()

    selected = controller.selected_device
    assert selected is not None, "a machine with inputs must get a selection"
    assert selected.is_wasapi, (
        f"the default selection must prefer a WASAPI device; got "
        f"{selected.label!r} (host API {selected.hostapi_name!r})"
    )
    assert not selected.is_default_input, (
        "test setup: PortAudio's reported default is the MME device, so a "
        "controller that merely trusted it would pick a non-WASAPI device"
    )
    assert selected.hostapi_index == WASAPI


def test_falls_back_to_the_default_device_when_no_wasapi_input_exists(
    make_controller: Callable[..., CaptureController]
) -> None:
    sd = FakeSounddevice(
        devices=NO_WASAPI_DEVICES, hostapis=HOSTAPIS, default_input=2
    )
    controller = make_controller(sd_module=sd)

    controller.refresh_devices()

    selected = controller.selected_device
    assert selected is not None
    assert selected.index == 2, (
        f"with no WASAPI input the fallback is PortAudio's default device "
        f"(index 2), got {selected.label!r} at index {selected.index}"
    )
    assert selected.is_default_input


def test_falls_back_to_the_first_input_when_there_is_no_default_either(
    make_controller: Callable[..., CaptureController]
) -> None:
    sd = FakeSounddevice(
        devices=NO_WASAPI_DEVICES, hostapis=HOSTAPIS, default_input=None
    )
    controller = make_controller(sd_module=sd)

    devices = controller.refresh_devices()

    assert devices, "test setup: there are still input devices"
    selected = controller.selected_device
    assert selected is not None, (
        "no WASAPI and no default still leaves usable inputs; the picker must "
        "choose one rather than showing nothing"
    )
    assert selected == devices[0], (
        f"the last fallback is the first input device {devices[0].label!r}, got "
        f"{selected.label!r}"
    )


def test_an_empty_device_list_is_handled_without_raising(
    make_controller: Callable[..., CaptureController]
) -> None:
    """"No microphone" is a state the GUI has to render, not an exception."""
    sd = FakeSounddevice(devices=[], hostapis=[], default_input=None)
    controller = make_controller(sd_module=sd)
    seen: list[Any] = []
    controller.devices_changed.connect(seen.append)

    devices = controller.refresh_devices()

    assert devices == []
    assert list(controller.devices) == []
    assert controller.selected_device is None
    assert len(seen) == 1, "devices_changed must fire even when the list is empty"
    assert list(seen[0]) == []
    assert controller.state is CaptureState.STOPPED, (
        "an empty device list is not an error state"
    )


def test_refresh_devices_is_repeatable(
    make_controller: Callable[..., CaptureController]
) -> None:
    """PortAudio's table changes when hardware is plugged in; re-enumerating is
    the only way to notice."""
    controller = make_controller(sd_module=FakeSounddevice(default_input=0))
    seen: list[Any] = []
    controller.devices_changed.connect(seen.append)

    first = controller.refresh_devices()
    second = controller.refresh_devices()

    assert [d.index for d in first] == [d.index for d in second]
    assert len(seen) == 2
    assert controller.selected_device is not None
    assert controller.selected_device.is_wasapi


def test_select_device_none_clears_the_selection(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller(sd_module=FakeSounddevice())
    controller.refresh_devices()
    assert controller.selected_device is not None

    controller.select_device(None)

    assert controller.selected_device is None


def test_select_device_picks_the_named_device(
    make_controller: Callable[..., CaptureController]
) -> None:
    """Device 0 is also list position 0, so this holds under either reading of
    the argument."""
    controller = make_controller(sd_module=FakeSounddevice())
    devices = controller.refresh_devices()
    assert devices[0].index == 0, "test setup: the first input device is index 0"

    controller.select_device(0)

    selected = controller.selected_device
    assert selected is not None
    assert selected.index == 0
    assert selected.hostapi_index == MME


# ==========================================================================
# start() / stop() over a file-backed pipeline
# ==========================================================================

def test_a_fresh_controller_is_stopped(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller()

    assert controller.state is CaptureState.STOPPED
    assert controller.pipeline is None, "nothing is constructed before start()"
    assert isinstance(controller.config, AudioConfig)


def test_poll_before_start_returns_stopped_zeroed_stats(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller()

    stats = controller.poll()

    assert isinstance(stats, UiStats)
    assert stats.state is CaptureState.STOPPED
    assert stats.frames_captured == 0
    assert stats.chunks_emitted == 0
    assert stats.latency_ms == pytest.approx(0.0), (
        "device latency is meaningless with no stream open"
    )


def test_start_then_stop_transitions_state_and_emits(
    replay: Callable[..., Any]
) -> None:
    controller, _cfg, _n = replay(realtime=True, loop=True)
    states: list[CaptureState] = []
    controller.state_changed.connect(states.append)

    assert controller.start() is True, "a file-backed start() must succeed"
    assert controller.state is CaptureState.RUNNING
    assert isinstance(controller.pipeline, AudioPipeline)
    assert isinstance(controller.pipeline.sink, LatestChunkSink), (
        "the pipeline's sink must be the recording sink, not a Qt object"
    )

    assert controller.stop() is True
    assert controller.state is CaptureState.STOPPED

    assert states[:2] == [CaptureState.RUNNING, CaptureState.STOPPED], (
        f"state_changed must report the transitions in order, got {states}"
    )


def test_a_stopped_controller_leaves_no_audio_thread_behind(
    replay: Callable[..., Any]
) -> None:
    controller, _cfg, _n = replay(realtime=True, loop=True)
    assert controller.start() is True
    assert wait_until(lambda: bool(audio_threads())), "the pipeline never ran"

    assert controller.stop() is True

    assert wait_until(lambda: not audio_threads(), timeout=5.0), (
        f"threads outlived stop(): {audio_threads()}"
    )


def test_a_full_replay_matches_the_window_hop_arithmetic(
    replay: Callable[..., Any]
) -> None:
    """The counters the GUI shows must be the counters the file implies."""
    w, h, n = 100, 50, 1000
    controller, cfg, _n = replay(window_ms=w, hop_ms=h, n_frames=n)
    assert cfg.window_frames == w and cfg.hop_frames == h, "test setup"

    assert controller.start() is True
    pipeline = controller.pipeline
    assert pipeline is not None
    assert pipeline.wait_until_finished(timeout=TIMEOUT) is True, (
        f"the replay never drained; error={pipeline.error!r}"
    )

    stats = controller.poll()

    assert isinstance(stats, UiStats)
    assert stats.state is CaptureState.RUNNING
    assert stats.frames_captured == n, (
        f"frames_captured must equal the file's {n} frames, got "
        f"{stats.frames_captured}"
    )
    assert stats.chunks_emitted == n_windows(n, w, h), (
        f"a {n}-frame file at W={w} H={h} yields exactly {n_windows(n, w, h)} "
        f"full windows, got {stats.chunks_emitted}"
    )
    assert stats.chunks_dropped == 0, "BLOCK policy must never drop a chunk"
    assert stats.overruns == 0, "the ring dwarfs the file"
    assert stats.peak_level > 0.0, "a non-silent ramp must move the meters"
    assert stats.display_peak >= stats.peak_level - 1e-6, (
        "display_peak is the held peak, so it can never read below the raw one"
    )
    assert controller.stop() is True


def test_stats_updated_reports_rising_counters(
    replay: Callable[..., Any], qtbot: Any
) -> None:
    """The QTimer must actually drive poll() while running."""
    controller, _cfg, _n = replay(realtime=True, loop=True, hop_ms=50)
    collected: list[UiStats] = []
    controller.stats_updated.connect(collected.append)

    assert controller.start() is True
    qtbot.waitUntil(lambda: len(collected) >= 5, timeout=TIMEOUT_MS)
    qtbot.waitUntil(
        lambda: collected[-1].chunks_emitted > 0, timeout=TIMEOUT_MS
    )

    frames = [s.frames_captured for s in collected]
    chunks = [s.chunks_emitted for s in collected]
    assert all(isinstance(s, UiStats) for s in collected)
    assert frames == sorted(frames), f"frames_captured must never fall: {frames}"
    assert chunks == sorted(chunks), f"chunks_emitted must never fall: {chunks}"
    assert frames[-1] > frames[0], (
        f"a running capture must report more frames over time: {frames}"
    )
    assert collected[-1].elapsed_s > 0.0, "elapsed_s must advance while running"
    assert all(s.state is CaptureState.RUNNING for s in collected)

    assert controller.stop() is True


def test_stats_updated_is_only_ever_emitted_from_the_gui_thread(
    replay: Callable[..., Any], qtbot: Any
) -> None:
    """Qt may never be touched from an audio thread.  This is the assertion the
    whole poll-on-a-timer design exists to satisfy."""
    controller, _cfg, _n = replay(realtime=True, loop=True)
    main_ident = threading.get_ident()
    idents: list[int] = []

    controller.stats_updated.connect(lambda _s: idents.append(threading.get_ident()))

    assert controller.start() is True
    qtbot.waitUntil(lambda: len(idents) >= 5, timeout=TIMEOUT_MS)
    assert controller.stop() is True

    assert set(idents) == {main_ident}, (
        f"stats_updated fired on {sorted(set(idents) - {main_ident})}; the "
        f"GUI thread is {main_ident}.  The sink runs on the consumer thread "
        "and must never emit a signal itself."
    )


def test_the_timer_stops_emitting_once_the_capture_is_stopped(
    replay: Callable[..., Any], qtbot: Any
) -> None:
    controller, _cfg, _n = replay(realtime=True, loop=True)
    collected: list[UiStats] = []
    controller.stats_updated.connect(collected.append)

    assert controller.start() is True
    qtbot.waitUntil(lambda: len(collected) >= 3, timeout=TIMEOUT_MS)
    assert controller.stop() is True

    qtbot.wait(int(QUIET_S * 1000))
    settled = len(collected)
    qtbot.wait(int(QUIET_S * 1000))

    assert len(collected) == settled, (
        "the poll timer must be stopped along with the capture, not left "
        "burning event-loop time forever"
    )


def test_start_failure_sets_error_and_does_not_raise(
    make_controller: Callable[..., CaptureController]
) -> None:
    """A device that will not open is the common case; it must never escape."""
    def exploding_builder(*args: Any, **kwargs: Any) -> Any:
        raise RuntimeError("PortAudio refused to open the device")

    controller = make_controller(builder=exploding_builder)
    controller.refresh_devices()
    errors: list[str] = []
    states: list[CaptureState] = []
    controller.error_occurred.connect(errors.append)
    controller.state_changed.connect(states.append)

    result = controller.start()          # must not raise

    assert result is False, "a failed start() reports False rather than raising"
    assert controller.state is CaptureState.ERROR
    assert CaptureState.ERROR in states, "state_changed must report the failure"
    assert errors, "error_occurred must carry a human-readable message"
    assert isinstance(errors[0], str) and errors[0].strip()


def test_a_failed_start_can_still_be_stopped(
    make_controller: Callable[..., CaptureController]
) -> None:
    def exploding_builder(*args: Any, **kwargs: Any) -> Any:
        raise RuntimeError("no device")

    controller = make_controller(builder=exploding_builder)
    assert controller.start() is False

    assert controller.stop() is True, "cleanup after a failed start must work"
    assert controller.state is CaptureState.STOPPED


def test_stop_before_start_is_safe(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller()

    assert controller.stop() is True, "stopping a never-started controller is a no-op"
    assert controller.state is CaptureState.STOPPED
    assert controller.pipeline is None


def test_stop_twice_is_safe(replay: Callable[..., Any]) -> None:
    controller, _cfg, _n = replay(realtime=True, loop=True)
    assert controller.start() is True

    assert controller.stop() is True
    assert controller.stop() is True, "stop() must be idempotent"
    assert controller.stop() is True, "and still idempotent"
    assert controller.state is CaptureState.STOPPED


def test_stop_emits_state_changed_only_on_a_real_transition(
    replay: Callable[..., Any]
) -> None:
    controller, _cfg, _n = replay(realtime=True, loop=True)
    assert controller.start() is True
    assert controller.stop() is True

    states: list[CaptureState] = []
    controller.state_changed.connect(states.append)
    assert controller.stop() is True

    assert states == [], (
        f"a redundant stop() must not re-announce STOPPED, got {states}"
    )


# ==========================================================================
# set_geometry()
# ==========================================================================

def test_set_geometry_updates_the_config_while_stopped(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller(config=make_config(window_ms=100, hop_ms=50))

    assert controller.set_geometry(200, 80) is True

    assert controller.config.window_ms == 200
    assert controller.config.hop_ms == 80
    assert controller.config.overlap_frames == 120, (
        "overlap is derived, so the new geometry must recompute it"
    )


def test_set_geometry_reconfigures_a_running_pipeline(
    replay: Callable[..., Any]
) -> None:
    """window_ms/hop_ms live in a frozen dataclass swapped atomically; no
    restart of the audio device is needed."""
    controller, _cfg, _n = replay(window_ms=100, hop_ms=50, realtime=True, loop=True)
    assert controller.start() is True
    pipeline = controller.pipeline
    assert pipeline is not None
    assert wait_until(lambda: controller.poll().chunks_emitted > 0), (
        f"the stream never got going; error={pipeline.error!r}"
    )

    assert controller.set_geometry(200, 50) is True

    assert controller.config.window_ms == 200
    assert pipeline.config.window_ms == 200, (
        "a running pipeline must be reconfigured, not merely remembered"
    )
    assert pipeline.config.hop_ms == 50
    assert controller.state is CaptureState.RUNNING, (
        "reconfiguring is not a restart"
    )
    assert pipeline.error is None
    assert controller.stop() is True


@pytest.mark.parametrize(
    ("window_ms", "hop_ms"),
    [
        (100, 200),        # hop > window: this pipeline is for overlapping windows
        (50, 500),
    ],
)
def test_a_hop_larger_than_the_window_is_rejected(
    window_ms: int,
    hop_ms: int,
    make_controller: Callable[..., CaptureController],
) -> None:
    original = make_config(window_ms=100, hop_ms=50)
    controller = make_controller(config=original)
    errors: list[str] = []
    controller.error_occurred.connect(errors.append)

    result = controller.set_geometry(window_ms, hop_ms)   # must not raise

    assert result is False
    assert errors, "the user must be told why the geometry was refused"
    assert isinstance(errors[0], str) and errors[0].strip()
    assert controller.config.window_ms == 100, "config must be left untouched"
    assert controller.config.hop_ms == 50
    assert controller.config == original


def test_a_sub_frame_geometry_is_rejected(
    make_controller: Callable[..., CaptureController]
) -> None:
    """A window that rounds to zero frames would emit empty chunks and make
    overlap_ratio divide by zero; window_ms > 0 alone does not catch it."""
    original = make_config(window_ms=100, hop_ms=100, sample_rate=100)
    assert original.window_frames == 10, "test setup: 1 ms == 0.1 frames here"
    controller = make_controller(config=original)
    errors: list[str] = []
    controller.error_occurred.connect(errors.append)

    result = controller.set_geometry(5, 5)   # 0.5 frames -> rounds to 0

    assert result is False, "a sub-frame window must be refused"
    assert errors
    assert controller.config == original, (
        f"a rejected geometry must leave config unchanged, got {controller.config}"
    )


def test_a_rejected_geometry_does_not_disturb_a_running_stream(
    replay: Callable[..., Any]
) -> None:
    controller, cfg, _n = replay(window_ms=100, hop_ms=50, realtime=True, loop=True)
    assert controller.start() is True
    assert wait_until(lambda: controller.poll().chunks_emitted > 0)

    assert controller.set_geometry(100, 400) is False

    assert controller.config == cfg, "config must survive a rejected change"
    assert controller.state is CaptureState.RUNNING, (
        "a validation failure is a user error, not a capture failure"
    )
    before = controller.poll().chunks_emitted
    assert wait_until(lambda: controller.poll().chunks_emitted > before), (
        "the stream must keep producing after a rejected reconfigure"
    )
    assert controller.stop() is True


def test_set_geometry_zero_is_rejected(
    make_controller: Callable[..., CaptureController]
) -> None:
    original = make_config()
    controller = make_controller(config=original)
    errors: list[str] = []
    controller.error_occurred.connect(errors.append)

    assert controller.set_geometry(0, 0) is False
    assert controller.set_geometry(-100, 50) is False
    assert errors, "both refusals must be reported"
    assert controller.config == original


# ==========================================================================
# poll() surfacing a dead pipeline
# ==========================================================================

def test_poll_surfaces_a_dead_pipeline_as_error(
    tmp_path: Any, make_controller: Callable[..., CaptureController]
) -> None:
    """Background threads never re-raise; poll() is the GUI's only chance to
    notice that capture died."""
    cfg = make_config(window_ms=100, hop_ms=50, ring_seconds=1.0)
    assert cfg.ring_frames == 1000, "test setup: the ring must be 1000 frames"
    path = write_wav(tmp_path / "dead.wav", ramp_int16(4000), cfg.sample_rate)

    # Blocks larger than the ring make ring.write raise on the source thread.
    controller = make_controller(
        config=cfg, builder=file_builder(path, blocksize=1500)
    )
    controller.refresh_devices()
    errors: list[str] = []
    states: list[CaptureState] = []
    controller.error_occurred.connect(errors.append)
    controller.state_changed.connect(states.append)

    assert controller.start() is True
    pipeline = controller.pipeline
    assert pipeline is not None
    assert wait_until(lambda: pipeline.error is not None), (
        "test setup: the oversized block must kill the source thread"
    )

    stats = controller.poll()

    assert controller.state is CaptureState.ERROR, (
        "a pipeline whose error is set must move the controller to ERROR"
    )
    assert stats.state is CaptureState.ERROR
    assert CaptureState.ERROR in states
    assert errors, "error_occurred must describe the failure to the user"
    assert isinstance(errors[0], str) and errors[0].strip()
    assert controller.stop() is True


def test_a_dead_pipeline_stops_the_poll_timer(
    tmp_path: Any, make_controller: Callable[..., CaptureController], qtbot: Any
) -> None:
    """Once capture has died there is nothing left to poll; the timer must not
    keep burning event-loop time (and re-announcing) forever."""
    cfg = make_config(window_ms=100, hop_ms=50, ring_seconds=1.0)
    path = write_wav(tmp_path / "dead2.wav", ramp_int16(4000), cfg.sample_rate)
    controller = make_controller(
        config=cfg, builder=file_builder(path, blocksize=1500)
    )
    controller.refresh_devices()
    collected: list[UiStats] = []
    controller.stats_updated.connect(collected.append)

    assert controller.start() is True
    pipeline = controller.pipeline
    assert pipeline is not None
    assert wait_until(lambda: pipeline.error is not None)

    qtbot.waitUntil(lambda: controller.state is CaptureState.ERROR, timeout=TIMEOUT_MS)
    qtbot.wait(int(QUIET_S * 1000))
    settled = len(collected)
    qtbot.wait(int(QUIET_S * 1000))

    assert len(collected) == settled, (
        f"the poll timer must stop once the pipeline is dead; it emitted "
        f"{len(collected) - settled} more times over {QUIET_S}s"
    )
    assert controller.stop() is True


# --------------------------------------------------------------------------
# Poll timer configuration
#
# Both of these are stated architectural requirements that nothing asserted.
# With Qt's default CoarseTimer the 33 ms interval is rounded to the Windows
# scheduler tick and runs at ~21 Hz instead of 30 -- a third of the UI frames
# silently missing, with nothing to indicate why.
# --------------------------------------------------------------------------


def test_poll_timer_is_precise_not_coarse() -> None:
    from PySide6.QtCore import Qt

    from echochamber.ui.controller import CaptureController

    controller = CaptureController()
    try:
        assert controller.poll_timer.timerType() == Qt.TimerType.PreciseTimer, (
            "a CoarseTimer rounds the 33 ms poll to the Windows scheduler tick "
            "and delivers ~21 Hz instead of the specified 30 Hz"
        )
    finally:
        controller.stop()


def test_poll_interval_is_the_specified_30hz() -> None:
    from echochamber.ui.controller import POLL_INTERVAL_MS, CaptureController

    assert POLL_INTERVAL_MS == 33, "the architecture specifies ~30 Hz GUI updates"
    controller = CaptureController()
    try:
        assert controller.poll_timer.interval() == POLL_INTERVAL_MS
    finally:
        controller.stop()


# -- ADB hotword trigger wiring ---------------------------------------------


def test_adb_trigger_is_disabled_by_default(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller()
    assert controller.adb_trigger_config.enabled is False
    assert controller.adb_trigger is None


def test_set_adb_trigger_enabled_flips_the_config(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller()
    assert controller.set_adb_trigger_enabled(True) is True
    assert controller.adb_trigger_config.enabled is True
    assert controller.set_adb_trigger_enabled(False) is True
    assert controller.adb_trigger_config.enabled is False


def test_ui_stats_carries_adb_trigger_fields() -> None:
    names = {f.name for f in dataclasses.fields(UiStats)}
    required = {
        "adb_trigger_backend",
        "adb_trigger_enabled",
        "adb_trigger_blocked",
        "adb_trigger_block_count",
        "adb_trigger_unblock_count",
        "adb_trigger_error",
    }
    missing = required - names
    assert not missing, f"UiStats is missing adb trigger fields: {sorted(missing)}"


def test_stopped_controller_reports_adb_trigger_off_in_stats(
    make_controller: Callable[..., CaptureController]
) -> None:
    controller = make_controller()
    stats = controller.poll()
    assert stats.adb_trigger_backend == "none"
    assert stats.adb_trigger_enabled is False
    assert stats.adb_trigger_blocked is False
